/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Единый список предстоящих встреч всех типов, отсортированный по `start`. */
        get: operations["Admin_listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Удалить бронирование.
         *
         *     Вне минимума ТЗ — для полноты CRUD.
         */
        delete: operations["Admin_deleteBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий (для управления владельцем). */
        get: operations["Admin_listEventTypes"];
        put?: never;
        /** @description Создание типа события. */
        post: operations["Admin_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить тип события по id.
         *
         *     Вне минимума ТЗ — для полноты CRUD.
         */
        get: operations["Admin_getEventType"];
        put?: never;
        post?: never;
        /**
         * @description Удалить тип события.
         *
         *     Вне минимума ТЗ — для полноты CRUD.
         */
        delete: operations["Admin_deleteEventType"];
        options?: never;
        head?: never;
        /**
         * @description Обновить тип события (частичное обновление).
         *
         *     Вне минимума ТЗ — для полноты CRUD.
         */
        patch: operations["Admin_updateEventType"];
        trace?: never;
    };
    "/api/admin/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить профиль владельца.
         *
         *     Возвращает единственный предзаданный профиль по умолчанию. Аутентификации нет.
         *     Опционально — для полноты.
         */
        get: operations["Admin_getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создание бронирования.
         *
         *     Бизнес-правила:
         *     - Правило занятости: пересечение интервалов [start, end) с любым существующим
         *     бронированием запрещено → 409 Conflict (SLOT_TAKEN).
         *     - Окно 14 дней: start должен попадать в [now, now+14d] → иначе 400 (INVALID_SLOT).
         *     - Сетка: start должен быть выровнен по durationMinutes от начала окна → иначе 400.
         *     - Тип события должен существовать → иначе 404 (EVENT_TYPE_NOT_FOUND).
         *     - `end` вычисляется сервером из durationMinutes выбранного типа.
         */
        post: operations["Public_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список доступных типов событий (видов брони).
         *     Страница видов брони для гостя.
         */
        get: operations["Public_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить тип события по id (публично, для страницы бронирования гостя). */
        get: operations["Public_getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты для выбранного типа события.
         *
         *     Бизнес-правила:
         *     - Окно 14 дней: слоты строятся только в пределах [now, now+14d].
         *     - Сетка: слоты выровнены по durationMinutes от начала окна.
         *     - Занятые слоты возвращаются с `available: false`.
         *     - Если переданы `from`/`to`, они обрезаются по 14-дневному окну.
         */
        get: operations["Public_getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Бронирование встречи. */
        Booking: {
            /** @description Идентификатор бронирования. */
            id: string;
            /** @description Идентификатор типа события. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало встречи (UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец встречи (UTC). Вычисляется сервером как start + durationMinutes.
             */
            end: string;
            /** @description Имя гостя. */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя.
             */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Момент создания бронирования (UTC).
             */
            createdAt: string;
        };
        /**
         * @description Тело запроса на создание бронирования.
         *
         *     Поле `end` не передаётся — оно вычисляется сервером из durationMinutes выбранного типа.
         */
        BookingCreate: {
            /** @description Идентификатор типа события. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Желаемое начало встречи (UTC). Должно быть выровнено по сетке durationMinutes.
             */
            start: string;
            /** @description Имя гостя. */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя.
             */
            guestEmail: string;
        };
        /** @description Единый формат ошибок. */
        Error: {
            /** @description Машиночитаемый код ошибки. */
            code: components["schemas"]["ErrorCode"];
            /** @description Человекочитаемое сообщение об ошибке. */
            message: string;
        };
        /**
         * @description Коды ошибок API.
         * @enum {string}
         */
        ErrorCode: "SLOT_TAKEN" | "EVENT_TYPE_NOT_FOUND" | "INVALID_SLOT" | "BOOKING_NOT_FOUND";
        /** @description Тип события (создаётся владельцем). */
        EventType: {
            /** @description Идентификатор типа события. Задаётся владельцем (произвольная строка). */
            id: string;
            /** @description Название типа события. */
            title: string;
            /** @description Описание типа события. */
            description: string;
            /**
             * Format: int32
             * @description Длительность события в минутах. Используется как шаг сетки слотов.
             */
            durationMinutes: number;
        };
        /**
         * @description Тело запроса на создание типа события.
         *
         *     По ТЗ владелец «задаёт id» → id включается в модель создания.
         */
        EventTypeCreate: {
            /** @description Идентификатор типа события, задаётся владельцем. */
            id: string;
            /** @description Название типа события. */
            title: string;
            /** @description Описание типа события. */
            description: string;
            /**
             * Format: int32
             * @description Длительность события в минутах.
             */
            durationMinutes: number;
        };
        /**
         * @description Тело запроса на частичное обновление типа события.
         *
         *     Все поля опциональны — обновляются только переданные. Вне минимума ТЗ.
         */
        EventTypeUpdate: {
            /** @description Название типа события. */
            title?: string;
            /** @description Описание типа события. */
            description?: string;
            /**
             * Format: int32
             * @description Длительность события в минутах.
             */
            durationMinutes?: number;
        };
        /**
         * @description Профиль владельца календаря.
         *
         *     Единственный предзаданный профиль по умолчанию. Аутентификация отсутствует.
         */
        Owner: {
            /** @description Идентификатор владельца. */
            id: string;
            /** @description Имя владельца. */
            name: string;
            /**
             * Format: email
             * @description Email владельца.
             */
            email: string;
        };
        /**
         * @description Вычисляемый слот в календаре.
         *
         *     Слоты строятся по сетке с шагом durationMinutes от начала окна.
         *     Занятые слоты возвращаются с флагом `available: false` (удобно для UI календаря).
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота (UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота (UTC). Равен start + durationMinutes.
             */
            end: string;
            /** @description Доступен ли слот для бронирования. */
            available: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Admin_listBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Admin_deleteBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 404 Not Found — тип события (или бронирование) не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Admin_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Admin_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 400 Bad Request — слот вне 14-дневного окна или невалидная сетка. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Admin_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 404 Not Found — тип события (или бронирование) не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Admin_deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 404 Not Found — тип события (или бронирование) не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Admin_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 400 Bad Request — слот вне 14-дневного окна или невалидная сетка. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 404 Not Found — тип события (или бронирование) не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Admin_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
    Public_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description 400 Bad Request — слот вне 14-дневного окна или невалидная сетка. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 404 Not Found — тип события (или бронирование) не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 409 Conflict — слот занят (пересечение интервалов). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Public_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Public_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 404 Not Found — тип события (или бронирование) не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Public_getSlots: {
        parameters: {
            query?: {
                /** @description Начало запрашиваемого диапазона (UTC). Опционально. */
                from?: string;
                /** @description Конец запрашиваемого диапазона (UTC). Опционально. */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Идентификатор типа события. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description 400 Bad Request — слот вне 14-дневного окна или невалидная сетка. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 404 Not Found — тип события (или бронирование) не найдены. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
